-- FIRST TRACK KHATANEX — Migration 005: extended customer details

USE first_track_khatanex;

ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS title VARCHAR(10) DEFAULT NULL AFTER id,
  ADD COLUMN IF NOT EXISTS business_name VARCHAR(150) DEFAULT NULL AFTER name,
  ADD COLUMN IF NOT EXISTS business_country VARCHAR(100) DEFAULT NULL AFTER business_name,
  ADD COLUMN IF NOT EXISTS display_name VARCHAR(150) DEFAULT NULL AFTER business_country,
  ADD COLUMN IF NOT EXISTS entity VARCHAR(100) DEFAULT NULL AFTER display_name,
  ADD COLUMN IF NOT EXISTS gstin VARCHAR(20) DEFAULT NULL AFTER entity,
  ADD COLUMN IF NOT EXISTS pan VARCHAR(20) DEFAULT NULL AFTER gstin,
  ADD COLUMN IF NOT EXISTS msme_number VARCHAR(50) DEFAULT NULL AFTER pan,
  ADD COLUMN IF NOT EXISTS mobile_country VARCHAR(100) DEFAULT NULL AFTER phone,

  ADD COLUMN IF NOT EXISTS business_state VARCHAR(100) DEFAULT NULL AFTER mobile_country,
  ADD COLUMN IF NOT EXISTS business_district VARCHAR(100) DEFAULT NULL AFTER business_state,
  ADD COLUMN IF NOT EXISTS business_pincode VARCHAR(20) DEFAULT NULL AFTER business_district,
  ADD COLUMN IF NOT EXISTS business_city VARCHAR(100) DEFAULT NULL AFTER business_pincode,
  ADD COLUMN IF NOT EXISTS business_landmark VARCHAR(255) DEFAULT NULL AFTER business_city,

  ADD COLUMN IF NOT EXISTS billing_state VARCHAR(100) DEFAULT NULL AFTER business_landmark,
  ADD COLUMN IF NOT EXISTS billing_district VARCHAR(100) DEFAULT NULL AFTER billing_state,
  ADD COLUMN IF NOT EXISTS billing_pincode VARCHAR(20) DEFAULT NULL AFTER billing_district,
  ADD COLUMN IF NOT EXISTS billing_city VARCHAR(100) DEFAULT NULL AFTER billing_pincode,
  ADD COLUMN IF NOT EXISTS billing_landmark VARCHAR(255) DEFAULT NULL AFTER billing_city,

  ADD COLUMN IF NOT EXISTS shipping_state VARCHAR(100) DEFAULT NULL AFTER billing_landmark,
  ADD COLUMN IF NOT EXISTS shipping_district VARCHAR(100) DEFAULT NULL AFTER shipping_state,
  ADD COLUMN IF NOT EXISTS shipping_pincode VARCHAR(20) DEFAULT NULL AFTER shipping_district,
  ADD COLUMN IF NOT EXISTS shipping_city VARCHAR(100) DEFAULT NULL AFTER shipping_pincode,
  ADD COLUMN IF NOT EXISTS shipping_landmark VARCHAR(255) DEFAULT NULL AFTER shipping_city;
