-- FIRST TRACK KHATANEX — Migration 006: user profile & business settings

-- USE first_track_khatanex;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS business_type VARCHAR(100) DEFAULT NULL AFTER business_name,
  ADD COLUMN IF NOT EXISTS gstin VARCHAR(20) DEFAULT NULL AFTER business_type,
  ADD COLUMN IF NOT EXISTS pan VARCHAR(20) DEFAULT NULL AFTER gstin,
  ADD COLUMN IF NOT EXISTS website VARCHAR(255) DEFAULT NULL AFTER pan,
  ADD COLUMN IF NOT EXISTS logo_path VARCHAR(255) DEFAULT NULL AFTER website,
  ADD COLUMN IF NOT EXISTS signature_path VARCHAR(255) DEFAULT NULL AFTER logo_path,
  ADD COLUMN IF NOT EXISTS address_line1 VARCHAR(255) DEFAULT NULL AFTER address,
  ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(255) DEFAULT NULL AFTER address_line1,
  ADD COLUMN IF NOT EXISTS city VARCHAR(100) DEFAULT NULL AFTER address_line2,
  ADD COLUMN IF NOT EXISTS state VARCHAR(100) DEFAULT NULL AFTER city,
  ADD COLUMN IF NOT EXISTS pincode VARCHAR(20) DEFAULT NULL AFTER state,
  ADD COLUMN IF NOT EXISTS country VARCHAR(100) DEFAULT 'India' AFTER pincode,
  ADD COLUMN IF NOT EXISTS currency VARCHAR(10) NOT NULL DEFAULT 'INR' AFTER country,
  ADD COLUMN IF NOT EXISTS tax_type VARCHAR(30) NOT NULL DEFAULT 'standard' AFTER currency,
  ADD COLUMN IF NOT EXISTS tcs_enabled TINYINT(1) NOT NULL DEFAULT 0 AFTER tax_type,
  ADD COLUMN IF NOT EXISTS tds_enabled TINYINT(1) NOT NULL DEFAULT 0 AFTER tcs_enabled,
  ADD COLUMN IF NOT EXISTS payment_terms VARCHAR(255) DEFAULT NULL AFTER tds_enabled;
